services:
  # Odoo server - WORKING VERSION
  odoo:
    container_name: odoo
    image: odoo:19.0
    restart: unless-stopped
    ports:
      - "9002:8069"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=odoo
      - DB_PASSWORD=odoo
      - DB_NAME=postgres
    volumes:
      - odoo19-data:/var/lib/odoo
      - ./odoo_config/conf:/etc/odoo
      - ./odoo_config/custom-addons:/mnt/extra-addons
    depends_on:
      - odoodb

  # Odoo database
  odoodb:
    container_name: odoodb
    image: postgres:16
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - dbdata:/var/lib/postgresql/data/pgdata

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:8
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_CONFIG_SERVER_MODE=False
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - odoodb

volumes:
  dbdata:
  odoo19-data:
  pgadmin-data:
